FROM apache/airflow:2.5.0

USER root
# Install any additional system dependencies here if needed

USER airflow
# Install Python dependencies
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
